### ISSUE TITLE
[Bug]: Gemini prompt field loses focus when trying to enter text

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#1604] opened 2024-04-04 10:57 UTC
### 插件版本号 | Version

1.4.5

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The title says for itself.

PS. Please, take a look at https://github.com/immersive-translate/immersive-translate/discussions/1598

[ImmersiveTranslate-Gemini-prompt-loses-focis-Video_2024-04-04_13-41-16.webm](https://github.com/immersive-translate/immersive-translate/assets/11407417/5ffcc277-1305-4587-997e-44fcf2ee023e)

**Comment by keyboard3** [comment] 2024-04-04 11:44
Sorry, I didn't understand this question.

**Comment by iG8R** [comment] 2024-04-04 11:58
As seen from the screenshot (pay attention to the bottom right corner where all keyboard key presses are displayed), when I tried to enter text in the "Prompt" field of the Gemini service, after the first entered character, this field lost focus, and all subsequent characters went somewhere else, except for this "Prompt" field.

**Comment by keyboard3** [comment] 2024-04-04 12:30
It looks like it's a problem with your input method.,I haven't been able to reproduce this situation here.,You should have this problem in any input box.

**Comment by keyboard3** [comment] 2024-04-04 13:35
I reproduced the issue and fixed it in the next release

**Comment by iG8R** [comment] 2024-04-04 13:41
Thanks a lot!

**Comment by iG8R** [comment] 2024-04-06 11:38
This bug still present in version 1.4.6

**Comment by keyboard3** [comment] 2024-04-06 11:44
> This bug is still present in version 1.4.6

next is 1.4.7 not 1.4.6

**Comment by iG8R** [comment] 2024-04-06 12:16
Sorry, for misunderstanding.
Even in version 1.4.7 this bug is still present, although it became a little better.
The focus is lost some time after interrupting entering text, and the green notification bar at the top is missing.

[ImmersiveTranslate-Gemini-prompt-bug-Video_2024-04-06_15-06-27.webm](https://github.com/immersive-translate/immersive-translate/assets/11407417/3975ad74-6aa2-4e73-b4cd-6c430aeeb1df)

**Comment by keyboard3** [comment] 2024-04-06 14:48
Yes, it is not fully fixed at the moment, and it will be completely fixed in the future

**Comment by keyboard3** [comment] 2024-04-18 03:27
1.4.9 fixed

**Closed by keyboard3** 2024-04-18 03:27 UTC
Labels: bug

**Comment by iG8R** [comment] 2024-04-18 08:47
Thanks a lot!
